# Generated by Django 2.0.6 on 2018-06-22 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=10, verbose_name='公司名称')),
                ('cworker', models.CharField(max_length=10, verbose_name='工头名称')),
                ('ctel', models.CharField(max_length=20, verbose_name='电话')),
            ],
            options={
                'verbose_name_plural': '装修公司',
            },
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=10, verbose_name='线路')),
            ],
            options={
                'verbose_name_plural': '线路',
            },
        ),
        migrations.CreateModel(
            name='logtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=10, verbose_name='日志类型')),
            ],
            options={
                'verbose_name_plural': '日志类型',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='门牌编号')),
                ('area', models.CharField(max_length=20, verbose_name='面积')),
                ('address', models.CharField(max_length=400, verbose_name='地址')),
                ('customertel', models.CharField(max_length=40, verbose_name='客户电话')),
                ('Dateofaudit', models.DateTimeField(blank=True, null=True, verbose_name='审核日期')),
                ('status', models.CharField(blank=True, max_length=40, null=True, verbose_name='店面状态')),
                ('companykey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.company', verbose_name='公司')),
                ('designerkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_name', to=settings.AUTH_USER_MODEL, verbose_name='设计师')),
                ('locationkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.logtype', verbose_name='线路')),
                ('managerkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_name', to=settings.AUTH_USER_MODEL, verbose_name='监理')),
            ],
            options={
                'verbose_name_plural': '门店',
            },
        ),
        migrations.CreateModel(
            name='storelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(blank=True, max_length=20, null=True, verbose_name='日志')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='记录日期')),
                ('logtypekey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.logtype', verbose_name='日志类型')),
                ('storekey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='店面')),
            ],
            options={
                'verbose_name_plural': '店面日志',
            },
        ),
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=10, verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '类型',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='typeskey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.types', verbose_name='类型'),
        ),
    ]
