# Generated by Django 2.0.6 on 2018-06-22 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='locationkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.location', verbose_name='线路'),
        ),
    ]
