# Generated by Django 2.0.6 on 2018-06-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20180624_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='supports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.CharField(max_length=50, verbose_name='活动')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='门店')),
            ],
            options={
                'verbose_name_plural': '活动',
            },
        ),
    ]
