# Generated by Django 2.0.6 on 2018-06-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_supports'),
    ]

    operations = [
        migrations.AddField(
            model_name='supports',
            name='type',
            field=models.IntegerField(default=3, verbose_name='类型'),
            preserve_default=False,
        ),
    ]
