# Generated by Django 2.0.6 on 2018-06-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_supports_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='serviceScore',
            field=models.CharField(default='4.2', max_length=10, verbose_name='服务评分'),
        ),
    ]
