# Generated by Django 2.0.6 on 2018-06-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_store_servicescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='serviceScore',
            field=models.CharField(default='5', max_length=10, verbose_name='服务评分'),
        ),
    ]
