# Generated by Django 2.0.6 on 2018-06-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20180624_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rankRate',
            field=models.CharField(default='95.0', max_length=10, verbose_name='高于其他店面'),
        ),
        migrations.AddField(
            model_name='store',
            name='score',
            field=models.CharField(default='5', max_length=10, verbose_name='店面评分'),
        ),
        migrations.AlterField(
            model_name='store',
            name='foodScore',
            field=models.CharField(default='5', max_length=10, verbose_name='商品评分'),
        ),
    ]
