# Generated by Django 2.0.6 on 2018-06-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_store_sellcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='deliveryPrice',
            field=models.IntegerField(default=1, verbose_name='商家配送'),
        ),
    ]
