# Generated by Django 2.0.6 on 2018-06-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_store_deliveryprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supports',
            old_name='support',
            new_name='description',
        ),
    ]
