# Generated by Django 2.0.6 on 2018-06-22 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='产品名称')),
                ('price', models.CharField(max_length=50, verbose_name='产品现价')),
                ('oldprice', models.CharField(max_length=50, verbose_name='产品原价')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('sellCount', models.IntegerField(verbose_name='销量')),
                ('rating', models.IntegerField(verbose_name='排行')),
                ('info', models.CharField(max_length=400, verbose_name='详情')),
                ('icon', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='小图')),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='大图')),
            ],
            options={
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
                ('rateType', models.CharField(choices=[('1', '差评'), ('0', '好评')], default='0', max_length=5)),
                ('text', models.CharField(max_length=400, verbose_name='评论内容')),
                ('avatar', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='头像')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
        ),
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=50, verbose_name='分类名称')),
            ],
            options={
                'verbose_name_plural': '种类',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.types', verbose_name='分类'),
        ),
    ]
