# Generated by Django 2.0.6 on 2018-06-22 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180622_2050'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='storelinegoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='产品')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='店铺')),
            ],
            options={
                'verbose_name_plural': '产品店铺对应关系表',
            },
        ),
        migrations.AlterModelOptions(
            name='ratings',
            options={'verbose_name_plural': '评价'},
        ),
    ]
