# Generated by Django 2.0.6 on 2018-06-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180622_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='gender',
            field=models.CharField(choices=[('-1', '普通'), ('2', '特价'), ('1', '折扣')], default='-1', max_length=5),
        ),
    ]
