# Generated by Django 2.0.6 on 2018-06-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20180624_1817'),
        ('goods', '0004_auto_20180624_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='stores',
            field=models.ManyToManyField(blank=True, to='store.Store', verbose_name='good_store'),
        ),
    ]
