# Generated by Django 2.0.6 on 2018-06-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goods_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storelinegoods',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='storelinegoods',
            name='store',
        ),
        migrations.DeleteModel(
            name='storelinegoods',
        ),
    ]
