# Generated by Django 2.0.6 on 2018-06-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20180624_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='icon',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image/%Y/%m', verbose_name='小图'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image/%Y/%m', verbose_name='大图'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='stores',
            field=models.ManyToManyField(blank=True, to='store.Store', verbose_name='可售店面'),
        ),
    ]
