# Generated by Django 2.0.6 on 2018-06-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20180624_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='types',
            old_name='typename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='types',
            old_name='sale',
            new_name='type',
        ),
    ]
